<?php

/**
 * What the checks in this directory should expect of a bake of docs/.
 *
 * Everything here is this site's rather than wikven's: another site publishes at another address,
 * builds other skins, and keeps other pages out of the index. The checks read these rather than
 * spelling them out, so the same entry point reads any bake -- an example under examples/, a
 * downstream wiki -- against that site's own answers.
 *
 * What is not here is anything the source tree already says. The number of entries a language bar
 * should carry and the order the navigation rows follow are derived from docs/ while the checks
 * run, because a target restated here would be a second copy of a fact that already has one.
 */

return [
	// Where this site is published. Every whole address the export writes -- the sitemap, og:url,
	// og:image, the canonical and hreflang links -- is built from it, and each is checked against
	// it. The same value as WikvenSiteUrl in docs/.wikven.yaml, which is what the bake itself reads.
	'site_url' => 'https://chaotic-ground.github.io/wikven/',

	// The skins docs/.wikven.yaml adds, each of which gets a whole second copy of the site under a
	// directory of this name. A copy is noindex wholesale and carries its own search bundle and its
	// own module bundle, so the checks need to know which directories are copies rather than pages.
	'skin_copies' => ['citizen', 'minerva'],

	// Every skin module the startup manifest may register: the two copies above plus the default
	// from default.yml. Exact, rather than a list of names not to find -- a check that only knows
	// the two skins that once rode in uninvited would pass the next one (#637).
	'skin_modules' => ['skins.citizen', 'skins.minerva', 'skins.vector'],

	// The pages this site means to keep out of the index. Search is a results page, and a results
	// page is not one to index; it carries __NOINDEX__ for that reason.
	'noindex_pages' => ['Search.html'],

	// The languages this site is written in, one search index each (#400).
	'search_languages' => ['en', 'ko'],

	// The language the pages are authored in. Marking a page for translation gives it a translation
	// page in this language too, and that page must not be indexed beside the source it restates
	// (#454).
	'source_language' => 'en',

	// A page with a sortable table on it, which is what makes the jquery.tablesorter check about
	// something (#483). Licenses is generated by the build and its table has always been sortable.
	'sortable_page' => 'Licenses.html',

	// A translated page in a script UniversalLanguageSelector bundles a font for, and the directory
	// that font is copied into. Without a page in such a script every webfont assertion passes
	// vacuously on an empty stylesheet, so the fixture is named rather than assumed.
	'webfont_language' => 'km',
	'webfont_directory' => 'KhmerOSbattambang',

	// The translated page whose navigation row proves a prevnext link is labelled with its target's
	// own translated title. Which page follows it comes from MediaWiki:Sidebar, and the title to
	// expect from that page's own source, so this names only the fixture.
	'prevnext_page' => 'Searching',
	'prevnext_language' => 'ko',

	// Pages that invoke a Lua module, and the answer Module:Example gives on each: the title of the
	// page it ran on. Spelled out per page rather than derived from the file name, because the file
	// name has underscores where the title has spaces (#465).
	'lua_pages' => [
		'Lua_modules.html' => 'Lua modules',
		'Lua_modules/ko.html' => 'Lua modules/ko'
	]
];
