#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

cd /var/www/html

php maintenance/run.php install \
  --server=http://localhost:4000 \
  --dbtype sqlite \
  --dbpath cache/ \
  --scriptpath '' \
  --pass adminpassword \
  MediaWiki \
  Admin

echo 'require_once '\''WikvenSettings.php'\'';' >> LocalSettings.php

php maintenance/run.php /var/www/html/extensions/Wikven/maintenance/build.php
rm -rf /workspace/dist/history/
