#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

cd /var/www/html

php maintenance/run.php install \
  --server=http://localhost:4000 \
  --dbtype sqlite \
  --dbpath cache/ \
  --scriptpath '' \
  --pass adminpassword \
  MediaWiki \
  Admin

echo 'require_once '\''WikvenSettings.php'\'';' >> LocalSettings.php

echo 'index' | php maintenance/run.php edit 'MediaWiki:Mainpage'
php maintenance/run.php /var/www/html/extensions/Wikven/maintenance/importWikitext.php

php maintenance/run.php runJobs
php maintenance/run.php purgeList
php maintenance/run.php rebuildFileCache --overwrite

php maintenance/run.php /var/www/html/extensions/Wikven/maintenance/buildStyles.php
php maintenance/run.php /var/www/html/extensions/Wikven/maintenance/rename.php
rm -rf /workspace/dist/history/
