#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

cd /var/www/html

php maintenance/install.php \
  --server=http://localhost:4000 \
  --dbtype sqlite \
  --dbpath cache/ \
  --scriptpath '' \
  --pass adminpassword \
  MediaWiki \
  Admin

echo 'require_once '\''WikvenSettings.php'\'';' >> LocalSettings.php

echo 'index' | php maintenance/edit.php 'MediaWiki:Mainpage'
php extensions/Wikven/maintenance/importWikitext.php

php maintenance/runJobs.php
php maintenance/purgeList.php
php maintenance/rebuildFileCache.php --overwrite

php extensions/Wikven/maintenance/buildStyles.php
php extensions/Wikven/maintenance/rename.php
rm -rf /workspace/dist/history/
