<?php

namespace MediaWiki\Extension\Wikven;

use ImportImages;
use Maintenance;
use MediaWiki\CommentStore\CommentStoreComment;
use MediaWiki\Content\ContentHandler;
use MediaWiki\Registration\ExtensionRegistry;
use MediaWiki\Revision\RevisionRecord;
use MediaWiki\Revision\RevisionStore;
use MediaWiki\Revision\SlotRecord;
use MediaWiki\Title\Title;
use MediaWiki\Title\TitleValue;
use MediaWiki\User\User;
use RebuildFileCache;
use RunJobs;
use Wikimedia\Rdbms\Platform\ISQLPlatform;

$IP = strval(getenv('MW_INSTALL_PATH')) !== ''
	? getenv('MW_INSTALL_PATH')
	: realpath(__DIR__ . '/../../../');

require_once "$IP/maintenance/Maintenance.php";

/** Build the static site: populate the wiki, then render each enabled skin in a fresh boot. */
class Build extends Maintenance {
	/** Fallback for the frozen timestamps when the caller names none; chosen only for being fixed. */
	private const FROZEN_TIMESTAMP = '20000101000000';

	/** Template the generated software list is written to, so an About page can place it itself. */
	private const SOFTWARE_TEMPLATE = 'Wikven software';

	public function __construct() {
		parent::__construct();
		$this->addDescription('Run the full wikven static-site build in a single process.');
	}

	public function execute() {
		// WIKVEN_BUILD_SKIN set renders one skin; orchestrator populates then spawns a pass per skin.
		if ((string)getenv('WIKVEN_BUILD_SKIN') !== '') {
			$this->renderSkin();
			return;
		}

		$ip = $GLOBALS['IP'];
		$own = __DIR__;

		$this->clearOutputDirectory();
		$this->setMainPage();
		$this->importImages("$ip/maintenance/importImages.php");
		$this->step(ImportWikitext::class, "$own/importWikitext.php");
		$this->assertMainPageExists();
		$this->setAboutPage();
		$this->setSettingsPage();
		$this->dropDeadPlaceLinks();
		$this->dropDeadCategoryLink();
		// Materialize content translations before RunJobs so rendered translation pages get exported.
		$this->step(BuildTranslations::class, "$own/buildTranslations.php");
		$this->runJobs("$ip/maintenance/runJobs.php");
		// Every page the export will hold now exists, and nothing writes another revision after
		// this, so this is where each page can be told when it was last edited, and by whom.
		$this->stampSourceHistory();
		$this->hideBuildAuthors();
		$this->forgetCachedRevisionRows();
		// The content is final here, so this is the last write the database needs and the passes
		// below can be readers of it.
		$this->freezePageTouched();

		$skins = $GLOBALS['wgWikvenSkins'] ?? [];
		if (!$skins) {
			$skins = [$GLOBALS['wgDefaultSkin']];
		}
		foreach ($skins as $skin) {
			$this->renderSkinPass($skin);
		}
	}

	/**
	 * Run the queue one type at a time, in name order: the runner otherwise shuffles the types.
	 *
	 * The search index is held back to the end. SifterSearch enqueues a rebuild for every revision
	 * inserted, and although a pending one absorbs the rest, each pass of the queue picks up
	 * whichever has arrived since. A bake was running Pagefind 21 times and leaving 20 dead
	 * generations of hashed index files in the output, since Pagefind writes into a directory rather
	 * than replacing it. Held back, it runs once, over the finished content.
	 */
	private function runJobs(string $file): void {
		$group = $this->getServiceContainer()->getJobQueueGroup();
		while (true) {
			$types = array_diff($group->getQueuesWithJobs(), [Search::INDEX_JOB]);
			if (!$types) {
				break;
			}
			sort($types);
			foreach ($types as $type) {
				$this->runJobsOfType($file, $type);
			}
		}
		if (in_array(Search::INDEX_JOB, $group->getQueuesWithJobs(), true)) {
			$this->runJobsOfType($file, Search::INDEX_JOB);
		}
	}

	private function runJobsOfType(string $file, string $type): void {
		$child = $this->createChild(RunJobs::class, $file);
		$child->setOption('type', $type);
		$child->execute();
	}

	/**
	 * Date every page at the commit that last changed the file it was written from, and credit
	 * that commit's author.
	 *
	 * The footer's "last edited" line reports a page's newest revision, and every revision here is
	 * written by the build: the import stamps its own instant, and a translatable page is written
	 * again by Translate's marker and once more per language by its render jobs. Chasing each of
	 * those writes means guessing which one lands last; stamping the rows once the content is
	 * final does not, and it is the same answer for all of them. What the file's mtime used to
	 * give was the moment CI cloned the repository -- one instant for every page, a different one
	 * for every bake of the same commit, and the one date SOURCE_DATE_EPOCH could not freeze
	 * (#406). git has the real one, and it is what the "View history" link opens.
	 *
	 * A page the history says nothing about -- one generated by the build, like Version and
	 * Settings, or a source file never committed -- keeps the frozen build clock, which dates it
	 * at the commit being built. That is true of the export as a whole, if not of the page.
	 */
	private function stampSourceHistory(): void {
		$source = rtrim((string)( $GLOBALS['wgWikvenSourceDirectory'] ?? '' ), '/');
		$history = SourceHistory::forSource($source, (string)( $GLOBALS['wgWikvenSourceHistoryFile'] ?? '' ));

		$services = $this->getServiceContainer();
		$build = User::newSystemUser(User::MAINTENANCE_SCRIPT_USER, ['steal' => true]);
		$authors = new SourceAuthors($services->getUserFactory(), $build);
		$actorStore = $services->getActorStore();
		$titleFactory = $services->getTitleFactory();

		$dbw = $this->getPrimaryDB();
		$pages = $dbw->newSelectQueryBuilder()
			->select(['page_namespace', 'page_title', 'page_latest'])
			->from('page')
			->caller(__METHOD__)
			->fetchResultSet();

		foreach ($pages as $page) {
			$title = $titleFactory->makeTitle((int)$page->page_namespace, $page->page_title);
			$change = $this->sourceChangeFor($title->getPrefixedText(), $history);
			if ($change === null) {
				continue;
			}

			$set = ['rev_timestamp' => $dbw->timestamp($change['timestamp'])];
			// No usable name among the author's gives the build's own account back, which is the
			// one it already has; hideBuildAuthors() below then leaves that page unattributed.
			$author = $authors->accountFor($change['authors']);
			if (!$author->equals($build)) {
				$set['rev_actor'] = $actorStore->acquireActorId($author, $dbw);
			}

			$dbw->newUpdateQueryBuilder()
				->update('revision')
				->set($set)
				->where(['rev_id' => (int)$page->page_latest])
				->caller(__METHOD__)
				->execute();
		}
	}

	/**
	 * What the history says about the file a page was written from, or null for a page the build
	 * wrote itself.
	 *
	 * SourceFile's naming convention answers which file that is for an imported page and for a
	 * translated one alike: "Skins" came from "Skins.wikitext" and "Skins/ko" from
	 * "Skins/ko.wikitext". The one page with no file of its own is the source-language page
	 * Translate adds ("Skins/en"), which follows the page it repeats.
	 *
	 * @return ?array{timestamp:int,authors:string[]}
	 */
	private function sourceChangeFor(string $prefixedText, SourceHistory $history): ?array {
		$files = [SourceFile::titleToFilename($prefixedText)];
		$slash = strrpos($prefixedText, '/');
		if ($slash !== false) {
			$files[] = SourceFile::titleToFilename(substr($prefixedText, 0, $slash));
		}

		foreach ($files as $file) {
			$timestamp = $history->timestamp($file);
			if ($timestamp !== null) {
				return ['timestamp' => $timestamp, 'authors' => $history->authors($file)];
			}
		}
		return null;
	}

	/**
	 * Stop the "last edited" lines naming the accounts the build writes under.
	 *
	 * The wiki is filled by maintenance scripts, so unless the source history just named a page's
	 * author, the account on its newest revision is the build's own: "Maintenance script" for
	 * everything the import and the page setters above wrote, and Translate's FuzzyBot for the
	 * translated pages its jobs render. Minerva's footer bar was offering that name to every
	 * reader as the person who last edited the page (#406). It names nobody, and the export has no
	 * user page, contributions or account for it to lead to.
	 *
	 * MediaWiki's own way of saying that a revision's author is not public is the DELETED_USER bit,
	 * and skins answer it without a name: Minerva emits no editor at all for a revision whose
	 * RevisionRecord::getUser() is null, leaving its bar to read "Last edited <when> by an
	 * anonymous user" -- which is what the export knows -- and with no name there is no link to a
	 * user page the export does not have. Vector's #footer-info-lastmod never carried an author.
	 * The pages that would report the bit itself, history and diffs, are not rendered, and page
	 * content hangs off a separate bit (DELETED_TEXT) this leaves alone.
	 */
	private function hideBuildAuthors(): void {
		$names = [User::MAINTENANCE_SCRIPT_USER];
		if (ExtensionRegistry::getInstance()->isLoaded('Translate')) {
			$names[] = (string)( $GLOBALS['wgTranslateFuzzyBotName'] ?? 'FuzzyBot' );
		}

		$dbw = $this->getPrimaryDB();
		$actors = $dbw->newSelectQueryBuilder()
			->select('actor_id')
			->from('actor')
			->where(['actor_name' => $names])
			->caller(__METHOD__)
			->fetchFieldValues();
		if (!$actors) {
			return;
		}

		// Assigned rather than or-ed in: a build never deletes a revision, so the field is 0 here.
		$dbw->newUpdateQueryBuilder()
			->update('revision')
			->set(['rev_deleted' => RevisionRecord::DELETED_USER])
			->where(['rev_actor' => $actors])
			->caller(__METHOD__)
			->execute();
	}

	/**
	 * Drop the cached copies of the revision rows the two steps above rewrote in place.
	 *
	 * RevisionStore keeps the row of a page's newest revision in the object cache for a week, keyed
	 * on the page and revision ids alone (RevisionStore::ROW_CACHE_KEY), and an edit in place
	 * changes neither id. The build reads most pages long before those two steps run -- the job
	 * queue parses every one of them -- so without this the skin passes, fresh processes over the
	 * same database-backed cache, would render each page with the date it had before it was
	 * stamped. Nothing else in the cache is touched: the Commons thumbnail lookups it also holds
	 * are why the build has one at all (see WikvenSettings.php).
	 */
	private function forgetCachedRevisionRows(): void {
		$cache = $this->getServiceContainer()->getMainWANObjectCache();
		$dbw = $this->getPrimaryDB();
		$pages = $dbw->newSelectQueryBuilder()
			->select(['page_id', 'page_latest'])
			->from('page')
			->caller(__METHOD__)
			->fetchResultSet();

		foreach ($pages as $page) {
			$cache->delete(
				$cache->makeGlobalKey(
					RevisionStore::ROW_CACHE_KEY,
					$dbw->getDomainID(),
					(int)$page->page_id,
					(int)$page->page_latest
				)
			);
		}
	}

	/**
	 * Freeze page_touched once content is final; wiki-page modules fold it into their version hash.
	 *
	 * Once, in the orchestrator, rather than once per skin pass: what it writes is content state,
	 * the same in every pass and derived from nothing a pass did, so a three-skin bake was running
	 * the same full-table update three times for two no-ops. It is also one of the two writes that
	 * kept a pass from being a reader of the database -- rebuildFileCache.php puts the wiki in
	 * read-only mode for its own duration, so a pass has no business writing around it -- and a
	 * reader is what a pass has to be to run beside another one (#407).
	 *
	 * Freezing here also means the pages are rendered with the frozen value rather than with
	 * whatever the import and the job queue left, since the passes now boot after it. That is the
	 * point of the freeze rather than a cost of moving it: SOURCE_DATE_EPOCH differs per commit,
	 * so a page_touched written under the frozen clock differs per commit too, and pinning it is
	 * what keeps the module version hashes embedded in the HTML stable between bakes.
	 */
	private function freezePageTouched(): void {
		$dbw = $this->getPrimaryDB();
		$dbw->newUpdateQueryBuilder()
			->update('page')
			->set(['page_touched' => $dbw->timestamp(self::FROZEN_TIMESTAMP)])
			->where(ISQLPlatform::ALL_ROWS)
			->caller(__METHOD__)
			->execute();

		// The modules read page_touched through LinkCache, not the row just written: this process
		// has warmed it filling the wiki, and its MediaWiki: entries are kept in the object cache
		// as well, which the passes below boot onto rather than build for themselves.
		$linkCache = $this->getServiceContainer()->getLinkCache();
		$pages = $dbw->newSelectQueryBuilder()
			->select(['page_namespace', 'page_title'])
			->from('page')
			->caller(__METHOD__)
			->fetchResultSet();
		foreach ($pages as $page) {
			$linkCache->invalidateTitle(new TitleValue((int)$page->page_namespace, $page->page_title));
		}
		$linkCache->clear();
	}

	/** Render one skin in a fresh boot by re-invoking this script with WIKVEN_BUILD_SKIN set. */
	private function renderSkinPass(string $skin): void {
		$self = PHP_BINARY;
		$prefix = [$self];
		// Embedded FrankenPHP leaves PHP_BINARY empty; re-run the binary itself as "<self> php-cli".
		if ($self === '' || !is_executable($self)) {
			$self = is_link('/proc/self/exe') ? ( readlink('/proc/self/exe') ?: '' ) : '';
			$prefix = [$self, 'php-cli'];
		}
		if ($self === '' || !is_executable($self)) {
			$this->fatalError('Wikven: cannot locate the PHP executable to render skins');
		}

		$command = array_merge($prefix, ['maintenance/run.php', __FILE__]);

		// The skin and the working directory are passed as arguments, scoped to the child alone, so
		// this process's own environment and cwd stay untouched while a skin renders. run.php resolves
		// relative to the install root, which the binary's php-cli requires, hence $GLOBALS['IP'] as
		// the child's cwd. An array argv also means the arguments never pass through a shell to be
		// quoted for.
		$descriptors = [0 => STDIN, 1 => STDOUT, 2 => STDERR];
		$pipes = [];
		$process = proc_open(
			$command,
			$descriptors,
			$pipes,
			$GLOBALS['IP'],
			['WIKVEN_BUILD_SKIN' => $skin] + getenv()
		);
		if ($process === false) {
			$this->fatalError("Wikven: could not start the build for skin '$skin'");
		}
		$exit = proc_close($process);

		if ($exit !== 0) {
			$this->fatalError("Wikven: build failed for skin '$skin' (exit $exit)");
		}
	}

	/** Render the already-imported content in the WIKVEN_BUILD_SKIN skin's output directory. */
	private function renderSkin(): void {
		$ip = $GLOBALS['IP'];
		$own = __DIR__;
		$dir = rtrim($GLOBALS['wgWikvenHtmlDirectory'], '/');
		if ($dir !== '' && !wfMkdirParents($dir)) {
			$this->fatalError("Wikven: could not create output directory $dir");
		}

		$this->step(RebuildFileCache::class, "$ip/maintenance/rebuildFileCache.php", ['overwrite' => true]);
		// RebuildFileCache renders in the content language; re-render translations in their own.
		$this->step(RetranslateChrome::class, "$own/retranslateChrome.php");
		// Every page is rendered by now: drop what each one recorded about the request that made it.
		$this->step(StripBuildStamps::class, "$own/stripBuildStamps.php");
		$this->step(BuildStyles::class, "$own/buildStyles.php");
		// Opt-in: bake ULS webfonts into a static stylesheet rewriteScripts links below.
		$this->step(BakeWebfonts::class, "$own/bakeWebfonts.php");
		$this->step(BuildScripts::class, "$own/buildScripts.php");
		$this->step(RewriteScripts::class, "$own/rewriteScripts.php");
		// Minerva takes no navigation from the sidebar, so its menu is filled in the rendered pages.
		$this->step(FillMinervaMenu::class, "$own/fillMinervaMenu.php");
		$this->step(StoreImages::class, "$own/storeImages.php");
		$this->step(Rename::class, "$own/rename.php");
		// Rename has expanded translation pages into "<Page>/<lang>.html"; resolve MyLanguage links now.
		$this->step(ResolveTranslationLinks::class, "$own/resolveTranslationLinks.php");

		// RebuildFileCache emits a per-page history/ tree the static host won't serve; drop it.
		$history = "$dir/history";
		if (is_dir($history)) {
			$this->removeDirectory($history);
		}
	}

	/** Empty the output dir (kept, may be a mount) so in-place edits don't leave stale output. */
	private function clearOutputDirectory(): void {
		$dir = rtrim($GLOBALS['wgWikvenHtmlDirectory'], '/');
		if ($dir === '' || !is_dir($dir)) {
			return;
		}
		$entries = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS),
			\RecursiveIteratorIterator::CHILD_FIRST
		);
		foreach ($entries as $entry) {
			if ($entry->isDir()) {
				rmdir($entry->getPathname());
			} else {
				unlink($entry->getPathname());
			}
		}
	}

	/** Recursively delete a directory and everything under it. */
	private function removeDirectory(string $dir): void {
		$entries = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS),
			\RecursiveIteratorIterator::CHILD_FIRST
		);
		foreach ($entries as $entry) {
			if ($entry->isDir()) {
				rmdir($entry->getPathname());
			} else {
				unlink($entry->getPathname());
			}
		}
		rmdir($dir);
	}

	/** Run one build step as a child maintenance script, applying $options first. */
	private function step(string $class, string $file, array $options = []): void {
		$child = $this->createChild($class, $file);
		foreach ($options as $name => $value) {
			$child->setOption($name, $value);
		}
		// A child returning false signals failure (e.g. a page didn't import); abort the build.
		if ($child->execute() === false) {
			$this->fatalError("Wikven: $class reported failures; aborting the build.");
		}
	}

	/** Import source-dir images into the File: namespace so pages render with local thumbnails. */
	private function importImages(string $file): void {
		$child = $this->createChild(ImportImages::class, $file);
		$child->setArg(0, rtrim($GLOBALS['wgWikvenSourceDirectory'], '/'));
		$child->setOption('extensions', implode(',', $GLOBALS['wgFileExtensions']));
		$child->setOption('skip-dupes', true);
		$child->execute();
	}

	/** Point the wiki's main page at $wgWikvenMainPage (imported later; see assertMainPageExists). */
	private function setMainPage(): void {
		// Whatever the installer made the main page, before the message below repoints it.
		$installed = Title::newMainPage();

		$title = Title::newFromText('MediaWiki:Mainpage');
		$user = User::newSystemUser(User::MAINTENANCE_SCRIPT_USER, ['steal' => true]);
		$page = $this->getServiceContainer()->getWikiPageFactory()->newFromTitle($title);

		$updater = $page->newPageUpdater($user);
		$content = ContentHandler::makeContent($GLOBALS['wgWikvenMainPage'], $title);
		$updater->setContent(SlotRecord::MAIN, $content);
		$updater->saveRevision(CommentStoreComment::newUnsavedComment('Set the main page'));

		$this->dropInstalledMainPage($installed, $user);
	}

	/**
	 * Delete the page the installer wrote, unless the source provides one by that name.
	 *
	 * It holds MediaWiki's "MediaWiki has been installed" boilerplate, which every bake was
	 * exporting as a page of the site. It is also the one page created before wikven's settings
	 * load, so its revision keeps the real clock and made the export differ between bakes.
	 */
	private function dropInstalledMainPage(Title $installed, User $user): void {
		if (!$installed->canExist() || !$installed->exists()) {
			return;
		}
		if (SourceFile::exists($installed->getPrefixedText())) {
			return;
		}
		$page = $this->getServiceContainer()->getWikiPageFactory()->newFromTitle($installed);
		$status = $this->getServiceContainer()
			->getDeletePageFactory()
			->newDeletePage($page, $user)
			->deleteUnsafe('Wikven: installer page, not part of the source');
		if (!$status->isOK()) {
			$this->output("Wikven: could not delete the installer's main page {$installed->getPrefixedText()}\n");
		}
	}

	/** Hide project links with no imported target (blank label to "-"), in the footer and menus. */
	private function dropDeadPlaceLinks(): void {
		// Label message (controls whether the link shows) => page-name message (the link's target).
		// Community portal is here for Minerva, which builds its menu from its own definitions and
		// reads this message directly; the other skins take it from MediaWiki:Sidebar.
		$places = [
			'Privacy' => 'privacypage',
			'Aboutsite' => 'aboutpage',
			'Disclaimers' => 'disclaimerpage',
			'Portal' => 'portal-url'
		];
		$user = User::newSystemUser(User::MAINTENANCE_SCRIPT_USER, ['steal' => true]);
		foreach ($places as $label => $pageMessage) {
			$target = Title::newFromText(wfMessage($pageMessage)->inContentLanguage()->text());
			if ($target && $target->exists()) {
				continue;
			}
			$title = Title::newFromText("MediaWiki:$label");
			$page = $this->getServiceContainer()->getWikiPageFactory()->newFromTitle($title);
			$updater = $page->newPageUpdater($user);
			$updater->setContent(SlotRecord::MAIN, ContentHandler::makeContent('-', $title));
			$updater->saveRevision(CommentStoreComment::newUnsavedComment('Disable dead footer link'));
		}
	}

	/** Blank "pagecategorieslink" so the category label isn't a dead Special:Categories link. */
	private function dropDeadCategoryLink(): void {
		$user = User::newSystemUser(User::MAINTENANCE_SCRIPT_USER, ['steal' => true]);
		$title = Title::newFromText('MediaWiki:Pagecategorieslink');
		$page = $this->getServiceContainer()->getWikiPageFactory()->newFromTitle($title);
		$updater = $page->newPageUpdater($user);
		$updater->setContent(SlotRecord::MAIN, ContentHandler::makeContent('', $title));
		$updater->saveRevision(CommentStoreComment::newUnsavedComment('Drop the dead category link'));
	}

	/**
	 * Generate a Settings page: the reader's own display choices, which a static export keeps in
	 * the browser rather than in a user account. It stands in for Special:MobileOptions, which is
	 * MobileFrontend's and which no bake writes, and it is a page rather than a panel so every
	 * skin can link to it.
	 *
	 * The controls themselves are drawn by ext.Wikven.appearance into the placeholders below;
	 * wikitext cannot carry a radio, and the choices mean nothing without the script anyway.
	 */
	private function setSettingsPage(): void {
		$name = $GLOBALS['wgWikvenSettingsPage'] ?? '';
		if ($name === '') {
			return;
		}
		$title = Title::newFromText($name);
		if (!$title || $title->exists()) {
			return;
		}

		// Special:MobileOptions is an empty form its own script fills, so this page is the same
		// empty form: Adder queues the modules, and MediaWiki draws the controls it would have
		// drawn there. Wikitext carries no <form>, and that stylesheet's layout rules all name
		// one, so fillMinervaMenu.php puts a real form inside this. The skin list is wikven's own,
		// and follows in a section of its own.
		$text = "<div id=\"wikven-settings-form\"></div>\n";
		if (count($GLOBALS['wgWikvenSkins'] ?? []) > 1) {
			$text .= $this->settingsSection(
				'wikven-skins',
				'wikven-skins-description',
				'wikven-appearance-skins'
			);
		}

		$user = User::newSystemUser(User::MAINTENANCE_SCRIPT_USER, ['steal' => true]);
		$page = $this->getServiceContainer()->getWikiPageFactory()->newFromTitle($title);
		$updater = $page->newPageUpdater($user);
		$updater->setContent(SlotRecord::MAIN, ContentHandler::makeContent($text, $title));
		$updater->saveRevision(CommentStoreComment::newUnsavedComment('Generate the settings page'));
	}

	/** One titled and described section of the settings page, around an empty placeholder. */
	private function settingsSection(string $title, string $description, string $id): string {
		return (
			'<div class="wikven-setting">'
			. '<div class="wikven-setting-title">'
			. $this->contentMsg($title)
			. '</div>'
			. '<div class="wikven-setting-description">'
			. $this->contentMsg($description)
			. '</div>'
			. "<div class=\"wikven-setting-control\" id=\"$id\"></div>"
			. "</div>\n"
		);
	}

	/**
	 * Give the site an About page, and MediaWiki's own footer link something to point at.
	 *
	 * An export has no Special:Version to send a reader to, and what that page holds -- what built
	 * this site -- is something a wiki's About page carries anyway. So this is one page rather than
	 * two: the software list is generated into {{Wikven software}}, and an About page transcludes
	 * it. A source page of the configured name is left exactly as written, so a site introduces
	 * itself in its own words and puts the list where it wants it (or leaves it out); with no
	 * source page, the build writes an introduction with the list under it.
	 *
	 * The footer entry is core's own "About {{SITENAME}}" place link, pointed here through
	 * MediaWiki:Aboutpage, which is where a reader of any wiki looks for it. Configured empty, no
	 * page is written and dropDeadPlaceLinks() blanks that entry as it does the other dead ones.
	 */
	private function setAboutPage(): void {
		$name = (string)( $GLOBALS['wgWikvenAboutPage'] ?? '' );
		$title = $name === '' ? null : Title::newFromText($name);
		if (!$title) {
			return;
		}

		$this->savePage('Template:' . self::SOFTWARE_TEMPLATE, $this->softwareList(), 'Generate the software list');
		if (!$title->exists()) {
			$this->savePage(
				$title->getPrefixedText(),
				$this->contentMsg('wikven-about-intro') . "\n\n{{" . self::SOFTWARE_TEMPLATE . "}}\n",
				'Generate the about page'
			);
		}
		$this->savePage('MediaWiki:Aboutpage', $title->getPrefixedText(), 'Point the About link at the about page');
	}

	/** The installed software, extensions and skins, as the wikitext {{Wikven software}} holds. */
	private function softwareList(): string {
		$db = $this->getServiceContainer()->getConnectionProvider()->getReplicaDatabase();
		$software = [
			['[https://www.mediawiki.org/ MediaWiki]', MW_VERSION],
			['[https://www.php.net/ PHP]', PHP_VERSION . ' (' . PHP_SAPI . ')'],
			[ucfirst($db->getType()), $db->getServerVersion()]
		];

		$text = $this->contentMsg('wikven-about-software') . "\n\n";
		$text .= '== ' . $this->contentMsg('version-software') . " ==\n";
		$text .=
			"{| class=\"wikitable\"\n! "
			. $this->contentMsg('version-software-product')
			. ' !! '
			. $this->contentMsg('version-software-version')
			. "\n";
		foreach ($software as [$product, $version]) {
			$text .= "|-\n| $product\n| $version\n";
		}
		$text .= "|}\n\n";

		// Split components into extensions and skins (skins live under skins/), each in its own section.
		$extensions = [];
		$skins = [];
		foreach (ExtensionRegistry::getInstance()->getAllThings() as $thingName => $credits) {
			if (str_contains($credits['path'] ?? '', '/skins/')) {
				$skins[$thingName] = $credits;
			} else {
				$extensions[$thingName] = $credits;
			}
		}
		$text .= $this->componentTable('version-extensions', 'version-ext-colheader-name', $extensions);
		$text .= $this->componentTable('version-skins', 'version-skin-colheader-name', $skins);
		return $text;
	}

	/** Write one page the build generates, creating or replacing it. */
	private function savePage(string $titleText, string $text, string $summary): void {
		$title = Title::newFromText($titleText);
		if (!$title) {
			return;
		}
		$user = User::newSystemUser(User::MAINTENANCE_SCRIPT_USER, ['steal' => true]);
		$page = $this->getServiceContainer()->getWikiPageFactory()->newFromTitle($title);
		$updater = $page->newPageUpdater($user);
		$updater->setContent(SlotRecord::MAIN, ContentHandler::makeContent($text, $title));
		$updater->saveRevision(CommentStoreComment::newUnsavedComment($summary));
	}

	/** A message in the wiki's content language (the pages here are content, not UI chrome). */
	private function contentMsg(string $key): string {
		return wfMessage($key)->inContentLanguage()->text();
	}

	/** A wikitext table of components with versions and project links, under the given messages. */
	private function componentTable(string $headingKey, string $nameColKey, array $things): string {
		if (!$things) {
			return '';
		}
		ksort($things);
		$text = '== ' . $this->contentMsg($headingKey) . " ==\n";
		$text .=
			"{| class=\"wikitable\"\n! "
			. $this->contentMsg($nameColKey)
			. ' !! '
			. $this->contentMsg('version-ext-colheader-version')
			. "\n";
		foreach ($things as $thingName => $credits) {
			$url = $credits['url'] ?? '';
			$label = $url !== '' ? "[$url $thingName]" : $thingName;
			$text .= "|-\n| $label\n| " . ( $credits['version'] ?? '' ) . "\n";
		}
		$text .= "|}\n";
		return $text;
	}

	/** Fail the build if the configured main page wasn't imported (else the site root 404s). */
	private function assertMainPageExists(): void {
		$name = $GLOBALS['wgWikvenMainPage'];
		$title = Title::newFromText($name);
		if (!$title || !$title->exists()) {
			$this->fatalError(
				"Wikven: the main page '$name' was not imported. Add a source file for it "
				. "(e.g. '$name.wikitext') or set \$wgWikvenMainPage to an imported page."
			);
		}
	}
}

$maintClass = Build::class;
require_once RUN_MAINTENANCE_IF_MAIN;
